added possibility to skip current episode while evaluating
niksaz/aido1 pull request #3
Opened 2020-07-21 12:54 UTC by bruce-willis

Параметр `directory` сделал опциональным, чтобы можно было запускать из редактора   
Минус: при запуске из консоли теперь надо писать `python -m scripts.evaluate --directory <directory_name>`, а не просто `python -m scripts.evaluate <directory_name>`,

2020-07-21 13:34 UTC, niksaz requested changes
Этого явно не хватало, спасибо.

2020-07-21 13:34 UTC, niksaz commented on scripts/evaluate.py
> +        env.env.env.render(mode=render_mode)
А тут этот вызов обязателен для регистрации handler-а?

Просто я не уверен, или до reset-а следует render вызывать, да и вроде регистрировать handler должно быть можно и без него.

2020-07-21 13:34 UTC, niksaz commented on scripts/evaluate.py
> +                env.env.env.render(mode=render_mode)
А тут можно просто done=True установить, чтобы потом тот основной цикл уже все переменные обновил также, как если бы эпизод естественно закончился?

2020-07-23 12:59 UTC, bruce-willis commented on scripts/evaluate.py
> +        env.env.env.render(mode=render_mode)
К сожалению да, т.к. handler вешается именно на `unwrapped.window`, которое ещё не создано до первого вызова рендеринга.
А при первом заходе в цикл вызовется `reset`, так что этот вызов нужен только для того чтобы создать окно

2020-07-23 13:00 UTC, bruce-willis commented on scripts/evaluate.py
> +                env.env.env.render(mode=render_mode)
К сожалению просто `done` здесь не доступен из-за области видимости, получилось сделать только с глобальной переменной (и 2 раза написав `global` - это обязательно, в одном месте было не достаточно)

2020-07-24 08:22 UTC, niksaz approved these changes
Отлично выглядит, спасибо.

2020-07-24 08:22 UTC, niksaz commented on scripts/evaluate.py
> +        env.env.env.render(mode=render_mode)
А, ок. Да и вроде конструктор в __init__ сам reset() вызывает, т.ч. все корректно тут должно быть.

2020-07-24 08:22 UTC, niksaz commented on scripts/evaluate.py
> +                env.env.env.render(mode=render_mode)
Точно, ты прав с областью видимости. Ага, global-ы обязательны.

2020-07-24 09:59 UTC, merged